apiVersion: apps/v1
kind: Deployment
metadata:
  name: license-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: license-service
  template:
    metadata:
      labels:
        app: license-service
    spec:
      containers:
      - name: license-service
        image: license-service:5.10.1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
